package echo

import (
	"context"
	"log"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

// Define a custom type for the context key
type contextKey string

// The key used to store and retrieve the request ID in the context
const requestIDKey contextKey = "requestID"

type EchoAdapter struct {
	userServiceInterface  UserServiceInterface
	loginServiceInterface LoginServiceInterface
}

func NewEchoAdapter(userServiceInterface UserServiceInterface, loginServiceInterface LoginServiceInterface) *EchoAdapter {
	return &EchoAdapter{
		userServiceInterface:  userServiceInterface,
		loginServiceInterface: loginServiceInterface,
	}
}

// Run implements ports.HTTPPort.
func (echoAdpater *EchoAdapter) Run() {
	e := echo.New()

	e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins: []string{"http://localhost:5173"},                                                                                       // Allow only your frontend origin
		AllowMethods: []string{http.MethodGet, http.MethodPost, http.MethodPut, http.MethodDelete, http.MethodOptions},                        // Include all necessary methods
		AllowHeaders: []string{echo.HeaderXRequestID, echo.HeaderOrigin, echo.HeaderContentType, echo.HeaderAccept, echo.HeaderAuthorization}, // Include standard and custom headers like Authorization
	}))

	e.Use(middleware.RequestID())

	e.GET("/", func(c echo.Context) error {
		return c.String(http.StatusOK, "Hello, World!")
	})

	e.GET("/v", func(c echo.Context) error {
		return c.String(http.StatusOK, "0.38")
	})

	userController := newUserController(echoAdpater.userServiceInterface)
	loginController := newLoginController(echoAdpater.loginServiceInterface)

	e.GET(
		"/v1/user",
		userController.getUser,
		jwtMiddleware(),
		wrapperMiddleware1,
		wrapperMiddleware2,
	)
	e.GET(
		"/user/test",
		userController.test,
		jwtMiddleware(),
		wrapperMiddleware1,
		wrapperMiddleware2,
	)
	e.POST("/v1/login", loginController.login, wrapperMiddleware1, wrapperMiddleware2)

	e.Logger.Fatal(e.Start(":8080"))

}

// Define the wrapper middleware
func wrapperMiddleware1(next echo.HandlerFunc) echo.HandlerFunc {
	return func(c echo.Context) error {
		log.Println("Before GET request 1")
		// Call the actual handler
		// Get the request ID generated by the RequestIDHandler middleware
		requestId := c.Response().Header().Get(echo.HeaderXRequestID)

		log.Println("wrapperMiddleware1:requestId", requestId)

		// Create a new context with the request ID value
		ctx := context.WithValue(c.Request().Context(), requestIDKey, requestId)

		// Update the request with the new context
		c.SetRequest(c.Request().WithContext(ctx))

		err := next(c)
		log.Println("After GET request 1")
		return err
	}
}

// Define the wrapper middleware
func wrapperMiddleware2(next echo.HandlerFunc) echo.HandlerFunc {
	return func(c echo.Context) error {
		log.Println("Before GET request 2")
		// Call the actual handler
		err := next(c)
		log.Println("After GET request 2")
		return err
	}
}
